# Generated by Django 6.0.2 on 2026-02-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeloequipo',
            old_name='fabricante',
            new_name='marca',
        ),
    ]
