# Generated by Django 6.0.2 on 2026-02-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0002_rename_fabricante_modeloequipo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='impresoras.dispositivo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
