# Generated by Django 6.0.2 on 2026-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0003_logdispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_sts1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_sts2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
