# Generated by Django 6.0.2 on 2026-02-23 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0004_dispositivo_ultimo_sts1_dispositivo_ultimo_sts2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
