# Generated by Django 6.0.2 on 2026-02-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0005_dispositivo_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='impresoras.modeloequipo'),
        ),
    ]
