# Generated by Django 6.0.2 on 2026-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0006_alter_dispositivo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_conexion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
