# Generated by Django 6.0.2 on 2026-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0007_dispositivo_ultima_conexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='ultima_conexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
