# Generated by Django 6.0.2 on 2026-02-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0008_alter_dispositivo_ultima_conexion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ej. v1.0.0', max_length=20, unique=True)),
                ('archivo_bin', models.FileField(help_text='Sube tu archivo .bin compilado en ESP-IDF', upload_to='firmwares/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('notas_version', models.TextField(blank=True, help_text='Cambios realizados en esta versión en C')),
                ('es_obligatoria', models.BooleanField(default=False, help_text='Fuerza a los equipos a actualizarse')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='firmware_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_instalados', to='impresoras.versionfirmware'),
        ),
    ]
