# Generated by Django 6.0.2 on 2026-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0009_versionfirmware_dispositivo_firmware_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='version_instalada',
            field=models.CharField(blank=True, default='Desconocida', max_length=20),
        ),
    ]
