# Generated by Django 6.0.2 on 2026-02-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0010_dispositivo_version_instalada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: iSmart ESP32 o Impresora Fiscal', max_length=100, unique=True)),
                ('icono', models.ImageField(blank=True, help_text='Sube un icono opcional', null=True, upload_to='iconos_fw/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='version_instalada',
            new_name='fw_ismart_instalado',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fw_printer_instalado',
            field=models.CharField(blank=True, default='Desconocida', max_length=20),
        ),
        migrations.AlterField(
            model_name='versionfirmware',
            name='notas_version',
            field=models.TextField(blank=True, help_text='Arreglado el problema con...'),
        ),
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='Ej: v1.0.0', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='versionfirmware',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='impresoras.proyectofirmware'),
        ),
    ]
