# Generated by Django 6.0.2 on 2026-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0011_proyectofirmware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='Ej: v1.0.0', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='versionfirmware',
            constraint=models.UniqueConstraint(fields=('proyecto', 'version'), name='unique_version_per_project'),
        ),
    ]
