# Generated by Django 6.0.2 on 2026-02-24 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0012_alter_versionfirmware_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(help_text='Ingrese el serial exacto del equipo.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='serial_invalido', message='El serial solo puede contener letras mayúsculas y números, sin espacios (ej. Z1F9999988).', regex='^[A-Z0-9]{10}$')]),
        ),
    ]
