# Generated by Django 6.0.2 on 2026-02-24 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0013_alter_dispositivo_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='Ej: v1.0.0', max_length=20, validators=[django.core.validators.RegexValidator(code='version_invalida', message='La versión debe tener un formato válido (ej. 1.0, v1.0.5). No se permiten letras sueltas ni espacios.', regex='^[vV]?\\d+(\\.\\d+)+$')]),
        ),
    ]
