# Generated by Django 6.0.2 on 2026-02-27 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0014_alter_versionfirmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='Ej: v1.0.0', max_length=20, validators=[django.core.validators.RegexValidator(code='version_invalida', message='La versión solo puede contener letras y números sin espacios (ej. 010000 o 020507GD00).', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
