# Generated by Django 6.0.2 on 2026-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0015_alter_versionfirmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='Ej: v010000', max_length=20),
        ),
    ]
