# Generated by Django 6.0.2 on 2026-03-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0016_alter_versionfirmware_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectofirmware',
            name='tipo_modulo',
            field=models.CharField(choices=[('ismart', 'Módulo iSmart'), ('impresora', 'Impresora Fiscal'), ('otro', 'Otro')], default='otro', help_text='¿A qué componente va dirigido?', max_length=20),
        ),
    ]
