# Generated by Django 6.0.2 on 2026-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0017_proyectofirmware_tipo_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectofirmware',
            name='tipo_modulo',
        ),
        migrations.AddField(
            model_name='versionfirmware',
            name='tipo_modulo',
            field=models.CharField(choices=[('ismart', 'Módulo iSmart'), ('impresora', 'Impresora Fiscal')], default='ismart', help_text='¿Para qué hardware es este archivo?', max_length=20),
        ),
    ]
