# Generated by Django 6.0.2 on 2026-03-10 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0018_remove_proyectofirmware_tipo_modulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionfirmware',
            name='version',
            field=models.CharField(help_text='iSmart: 020100 | Impresora: 020507GD00', max_length=15, validators=[django.core.validators.RegexValidator(code='version_hka_invalida', message='Formato inválido. Use 6 números (iSmart) o 6 números + 4 caracteres de Micro (Impresora). Ej: 020507 o 020507GD00', regex='^\\d{6}([A-Z0-9]{4})?$')]),
        ),
    ]
