# Generated by Django 6.0.3 on 2026-05-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0019_alter_versionfirmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='impresoras.modeloequipo'),
        ),
    ]
