# Generated by Django 6.0.3 on 2026-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0020_alter_dispositivo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ota_en_curso',
            field=models.BooleanField(default=False),
        ),
    ]
